INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('see login report','see login report','login_report.php', 1);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage person','manage person','man_person.php', 2);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage ambiance','manage ambiance','man_ambience.php', 3);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage course','manage course','man_course.php', 4);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage schedule','manage schedule','man_schedule.php', 5);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage class','manage class','man_class.php', 6);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('presence call','presence call','answer_presence.php', 7);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage school','manage school','man_school.php', 8);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage program','manage program','man_program.php', 9);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage datetime','manage datetime','man_datetime.php', 10);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('associate course to program','associate course to program','man_prog_course.php', 11);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage class_course','manage class_course','man_class_course.php', 12);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage enrollment','manage enrollment','man_enrollment.php', 13);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('associate ambiance to event','associate ambiance to event','man_event.php', 14);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('assign grade','assign grade','assign_grade.php', 15);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('see grade report','see grade report','grade_report.php', 16);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('see presence report','see presence report','presence_report.php', 17);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('perform payment','perform payment','perform_payment.php', 18);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('unlock class course','unlock class course','unlock_class_course.php', 19);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('program_course report','program_course report','show_program_course_report.php', 20);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('report card report','report card report','show_report_card_report.php', 21);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('historic school report','historic school report','show_historic_school_report.php', 22);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('statistical presence report','statistical presence report','stat_presence_report.php', 23);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage candidate','manage candidate','man_candidate.php', 24);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage documents','manage documents','man_documents.php', 25);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage candidates','manage candidates','admin_man_candidate.php', 26);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage agreement template','manage agreement template','man_agreement_template.php', 27);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage interested','manage interested','man_interested.php', 28);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('manage interesteds','manage interesteds','admin_man_interested.php', 29);
INSERT INTO Resource(short_name, long_name, link, RscGroupId) VALUES('presence map report','presence map report','presence_map_report.php', 30);

SELECT * from Resource;
