DELETE FROM ResourceGroup;
INSERT INTO ResourceGroup(name) VALUES('see login report');
INSERT INTO ResourceGroup(name) VALUES('manage person');
INSERT INTO ResourceGroup(name) VALUES('manage ambience');
INSERT INTO ResourceGroup(name) VALUES('manage course');
INSERT INTO ResourceGroup(name) VALUES('manage schedule');
INSERT INTO ResourceGroup(name) VALUES('manage class');
INSERT INTO ResourceGroup(name) VALUES('presence call');
INSERT INTO ResourceGroup(name) VALUES('manage school');
INSERT INTO ResourceGroup(name) VALUES('manage program');
INSERT INTO ResourceGroup(name) VALUES('manage datetime');
INSERT INTO ResourceGroup(name) VALUES('associate course to program');
INSERT INTO ResourceGroup(name) VALUES('associate class to course');
INSERT INTO ResourceGroup(name) VALUES('manage enrollment');
INSERT INTO ResourceGroup(name) VALUES('manage event');
INSERT INTO ResourceGroup(name) VALUES('assign grade');
INSERT INTO ResourceGroup(name) VALUES('grade report');
INSERT INTO ResourceGroup(name) VALUES('presence report');
INSERT INTO ResourceGroup(name) VALUES('perform payment');
INSERT INTO ResourceGroup(name) VALUES('unlock class course');
INSERT INTO ResourceGroup(name) VALUES('program_course report');
INSERT INTO ResourceGroup(name) VALUES('report card report');
INSERT INTO ResourceGroup(name) VALUES('historic school report');
INSERT INTO ResourceGroup(name) VALUES('statistical presence report');
INSERT INTO ResourceGroup(name) VALUES('manage candidate');
INSERT INTO ResourceGroup(name) VALUES('manage documents');
INSERT INTO ResourceGroup(name) VALUES('manage candidates');
INSERT INTO ResourceGroup(name) VALUES('manage agreement template');
INSERT INTO ResourceGroup(name) VALUES('manage interested');
INSERT INTO ResourceGroup(name) VALUES('manage interesteds');
INSERT INTO ResourceGroup(name) VALUES('presence map report');

SELECT * FROM ResourceGroup;
